services:
  raven:
    image: yoginth/raven:latest
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
